# Site settings
baseurl: "" # edit baseurl to simply '/' if using as your personal page (instead of a project page)
url: # the base hostname & protocol for your site, e.g. http://example.com
lang: 'ca'
google_analytics:

# Site info
titol: Arcadia escola autogestionària
mobile_titol: Arcadia
descripcio: "Arcadia es un proyecto de centro educativo autogestionario, cooperativo y comunitario en Barcelona."
color: #b80000

# Owner's info
author: 'Escola Arcàdia'
location: 'Carrer de la Constitució 25, 08014 Barcelona'
email: info@adabits.org
tel: '934 321 765'
logo: logo-dark.png
twitter: adab1ts

# Where things are
source: src
destination: _site
images_path: assets/images
theme_scripts_path: assets/scripts
theme_styles_path: assets/styles
theme_fonts_path: assets/fonts
data_dir: _data

# Collections
collections:
  contacte:
      output: false
  escola:
      output: false
  funcionament:
      output: false
  homepage:
      output: false
  image-blocks:
      output: false
  objectius:
      output: false
  pedagogia:
      output: false
  projecte:
      output: false
  testimonials:
      output: false
  pedagogia:
      output: false
  vertical-cards:
      output: false


# Site defaults frontmatters
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: basic
      sections: collection-name
      titular: "Títol per la capçalera de la pàgina"
      imatge_titular: "presentacio.jpg"
      color_pagina: verd
      titol_seo: "Títol per SEO"
      descripcio: "Descripció per SEO"
      paraules_clau: "Paraules clau separades per comes"


# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge

# Build settings
plugins:
  - jekyll-feed
plugins_dir:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock



# Outputting
permalink: pretty
timezone: Europe/Madrid
