# Site settings
baseurl: "" # edit baseurl to simply '/' if using as your personal page (instead of a project page)
url: # the base hostname & protocol for your site, e.g. http://example.com
lang: 'ca'
google_analytics:

# Site info
titol: Arcadia escola autogestionària
mobile_titol: Arcadia
descripcio: "Arcadia es un proyecto de centro educativo autogestionario, cooperativo y comunitario en Barcelona."
color: #b80000

# Owner's info
author: 'Escola Arcàdia'
location: 'Carrer de la Constitució 25, 08014 Barcelona'
email: info@adabits.org
tel: '934 321 765'
logo: logo-dark.png
twitter: adab1ts

# Where things are
source: src
destination: _site
images_path: assets/img
theme_scripts_path: assets/pillar/js
theme_styles_path: assets/pillar/css
theme_fonts_path: assets/pillar/fonts
#collections_dir: continguts # Optionally specify a directory if you want to store all your collections in the same place

data_dir: _data

# Collections
collections:
  #collections_dir: continguts # Optionally specify a directory if you want to store all your collections in the same place
  contacte:
      output: false
  escola:
      output: false
  funcionament:
      output: false
  homepage:
      output: false
  image-blocks:
      output: false
  objectius:
      output: false
  pedagogia:
      output: false
  pilars:
      output: false
  projecte:
      output: false
  testimonials:
      output: false
  teoria:
      output: false
  vertical-cards:
      output: false


# Site defaults frontmatters
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: basic
      sections: collection-name
      titular: "Títol per la capçalera de la pàgina"
      imatge_titular: "presentacio.jpg"
      color_pagina: verd
      titol_seo: "Títol per SEO"
      descripcio: "Descripció per SEO"
      paraules_clau: "Paraules clau separades per comes"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "imageblock"
    values:
      type: "imageblock"
      include: pillar/imageblock-left.html
      order: 1
      titol_seccio: "Títol de la secció"
      imatge: psicomotricidad.jpg
      descripcio_imatge: "descripció de la fotografia"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "feature-icon-boxed"
    values:
      type: "feature-icon-boxed"
      include: pillar/feature-icon-boxed.html
      order: 1
      titol_seccio: "Títol de la secció"
      fons: "bg--secondary"
      conceptes:
        - nom: "Autogestió"
          subtitol: "Cooperativisme autogestionari"
          icona: "Loop"
        - nom: "Educació Integral"
          subtitol: "Educació Integral"
          icona: "Pencil-Ruler"
        - nom: "Llibertat responsable"
          subtitol: "Llibertat "
          icona: "Bodybuilding"

  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "features-3-blocs"
    values:
      type: "features-3-blocs"
      include: pillar/features-3-blocs.html
      order: 1
      titol_seccio: "Títol de la secció"
      subtitol_seccio: "Lorem ipsum dolor sit amet"
      blocs:
        - nom: "Nom de la característica 1"
          subtitol: "Lorem ipsum dolor sit amet. Ut enim ad minim veniam."
          icona: "Loop"
          color_fons: secondary
        - nom: "Nom de la característica 2"
          subtitol: "Lorem ipsum dolor sit amet. Ut enim ad minim veniam."
          icona: "Bodybuilding"
          color_fons: primary
        - nom: "Nom de la característica 3"
          subtitol: "Lorem ipsum dolor sit amet. Ut enim ad minim veniam."
          icona: "Pencil-Ruler"
          color_fons: white

# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge

# Build settings
gems:
  - jekyll-feed
plugins_dir:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock



# Outputting
permalink: pretty
timezone: Europe/Madrid
