---
upload_path: "/src/assets/uploads/"
frontmatter_file_url_template: "/assets/uploads/"
body_file_url_template: "/assets/uploads/"
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
collections:
